title: Your awesome title
author: Grant Stevens
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 this is where the description is going.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
